version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db/ticketing

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticketing
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
